#ifndef VISQPROJECT_INCLUDE_VISQ_TRANSFORM_BORDER_EXTENSIONS_BORDER_TYPE_H_
#define VISQPROJECT_INCLUDE_VISQ_TRANSFORM_BORDER_EXTENSIONS_BORDER_TYPE_H_

namespace visq {

enum BorderType {
  Constant, Mirror
};

} // visq

#endif //VISQPROJECT_INCLUDE_VISQ_TRANSFORM_BORDER_EXTENSIONS_BORDER_TYPE_H_
